# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    robot -d  reports --loglevel TRACE --variable BROWSER:"headlesschrome"  --pythonpath ./resources tests/
  displayName: 'Tests Execution'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  continueOnError: true
  inputs:
    testResultsFiles: outputxunit.xml 
    searchFolder: 'D:\a\1\s\'
