name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      -users: actions/checkout@v2
      -users: actions/setup-node@v1
      -run: npm install -g bats
      -run: bats -v